from typing import Protocol

from ecommerce_agent.domain.models import BusinessMetric, Order, Product


class CommerceQueryPort(Protocol):
    async def search_products(self, query: str) -> list[Product]: ...
    async def list_orders(self, status: str | None = None) -> list[Order]: ...
    async def get_order(self, order_id: str) -> Order | None: ...
    async def get_metrics(self, name: str) -> list[BusinessMetric]: ...


class CommerceCommandPort(Protocol):
    async def update_product(self, product_id: str, fields: dict[str, object]) -> Product: ...
    async def ship_order(self, order_id: str, channel: str, tracking_number: str) -> Order: ...
